package it.polimi.ingsw.enumerations;

public enum ClientHandlerPhase {
    WAITING_GAME_MODE,
    WAITING_NICKNAME,
    WAITING_NUMBER_OF_PLAYERS,
    WAITING_IN_THE_LOBBY,
    READY_TO_START,
    WAITING_HIS_TURN,
    WAITING_STUDENT_TO_TRANSFERE,
    WAITING_MNMOVEMENT,
    SET_UP_FINISHED,

}
